### ISSUE TITLE
julia 1.11 doesn't have `Core.Intrinsics.arraylen`

### ISSUE THREAD

**Issue by avik-pal** [compintell/Tapir.jl#118]

**Comment by willtebbutt** [comment]
Yup -- there's going to be quite a bit of intrinsic upgrades needed to handle arrays in 1.11 due to the change to using the new buffer type (I forget exactly what it's called). Mostly likely I'll drop support for 1.10 when 1.11 is released.

**Comment by willtebbutt** [comment]
Closing in favour of #180 in order to only have one issue about this.
